# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  btree-benchmarks:
    dependencies:
    - base
    - btree
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: btree is a new Haskeleton package.
executables:
  btree:
    dependencies:
    - base
    - btree
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: YoEight/btree
library:
  dependencies:
  - base
  - vector
  - pretty
  source-dirs: library
license: MIT
maintainer: Yorick Laupa
name: btree
synopsis: A new Haskeleton package.
tests:
  btree-test-suite:
    dependencies:
    - base
    - btree
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
